### ISSUE TITLE
Unexpected error for call_service at pos 1: 'ZCLAttributeDef' object is not subscriptable

### ISSUE THREAD

**Issue by dhc25** [mdeweerd/zha-toolkit#158] opened 2023-04-21 22:56 UTC
Hi

I'm getting a pop error when running scan_device:

Failed to call service zha_toolkit.scan_device. Unknown error

Looking at the logs, this is the error -

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'ZCLAttributeDef' object is not subscriptable

This device scanned ok last week, and not sure what I've changed in my system to impact how these tools work.

Any guidance appreciated.

Thanks

**Comment by mdeweerd** [comment] 2023-04-22 10:02
`ZCLAttributeDef` is not referenced directly in the zha-toolkit code.

Hopefully the home-assistant.log can provide more information.
You can increase the log level so that we get more information - see [logger.setlevel in the README.md](https://github.com/mdeweerd/zha-toolkit#:~:text=by%20calling%20the-,logger.setlevel,-service.%20Example%20that)

**Comment by dhc25** [comment] 2023-04-22 10:56
Thanks for your feedback.
I restored to a backup prior to HA Core update, and it's working again now.
HA Core is now on 2023.3.6

Not sure if that was the issue... There may have been something else, but it is working.

**Comment by mdeweerd** [comment] 2023-04-22 12:31
I just upgraded to 2023.4.6 - the issue is reproducable there - apparently a change in the "internal" structure of the attributes definitions for a cluster that no longer has the "get" method...

**Comment by mdeweerd** [comment] 2023-04-22 13:51
Fixed in [v0.8.38](https://github.com/mdeweerd/zha-toolkit/releases/tag/v0.8.38) ( #159 )

**Closed by mdeweerd** 2023-04-22 13:51 UTC
